TASK_TYPE_CAMPAIGN_SYNC = "campaign_sync"
TASK_TYPE_VIDEO_RETRY = "video_retry"
TASK_TYPE_COMMENT_REPLY = "comment_reply"
TASK_TYPE_MESSAGE_REPLY = "message_reply"
TASK_TYPE_AFFILIATE_COMMENT = "affiliate_comment"
